//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lerp2APIEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lerp2APIEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Lerp2EditorMono {
            get {
                return ResourceManager.GetString("Lerp2EditorMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #if UNITY_EDITOR
        ///
        ///	using UnityEngine;
        ///	using UnityEditor;
        ///	using Lerp2API;
        ///	using Lerp2APIEditor;
        ///
        ///	[ExecuteInEditMode]
        ///	[InitializeOnLoad]
        ///    public class LerpedEditorHook : MonoBehaviour
        ///    {
        ///        static LerpedEditorHook()
        ///        {
        ///            Lerp2EditorMono.AddElement&lt;LerpedEditorHook&gt;();
        ///        }
        ///        void OnDestroy()
        ///        {
        ///			if(!EditorApplication.isPlayingOrWillChangePlaymode) 
        ///			{
        ///				LerpedCore.SetBool(LerpedCore.UnityBoot, false);
        ///			}
        ///        }
        ///    }
        ///
        ///#endif.
        /// </summary>
        internal static string LerpedEditorAttach {
            get {
                return ResourceManager.GetString("LerpedEditorAttach", resourceCulture);
            }
        }
    }
}
