var searchData=
[
  ['safeecall',['SafeECall',['../class_lerp2_a_p_i_1_1_safe_e_calls_1_1_safe_e_call.html',1,'Lerp2API::SafeECalls']]],
  ['safememorymappedfilehandle',['SafeMemoryMappedFileHandle',['../class_microsoft_1_1_win32_1_1_safe_handles_1_1_safe_memory_mapped_file_handle.html',1,'Microsoft::Win32::SafeHandles']]],
  ['safememorymappedviewhandle',['SafeMemoryMappedViewHandle',['../class_microsoft_1_1_win32_1_1_safe_handles_1_1_safe_memory_mapped_view_handle.html',1,'Microsoft::Win32::SafeHandles']]],
  ['saveentry',['SaveEntry',['../class_level_serializer_1_1_save_entry.html',1,'LevelSerializer']]],
  ['savegamemanager',['SaveGameManager',['../class_save_game_manager.html',1,'']]],
  ['saveonquit',['SaveOnQuit',['../class_unity_serializer_n_g_1_1_file_preferences_1_1_save_on_quit.html',1,'UnitySerializerNG::FilePreferences']]],
  ['scaneventargs',['ScanEventArgs',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_core_1_1_scan_event_args.html',1,'ICSharpCode::SharpZipLib::Core']]],
  ['scanfailureeventargs',['ScanFailureEventArgs',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_core_1_1_scan_failure_event_args.html',1,'ICSharpCode::SharpZipLib::Core']]],
  ['sceneindex',['SceneIndex',['../class_scene_index.html',1,'']]],
  ['scrollview',['ScrollView',['../class_scroll_view.html',1,'']]],
  ['semaphoreslim',['SemaphoreSlim',['../class_system_1_1_threading_1_1_semaphore_slim.html',1,'System::Threading']]],
  ['serializationhelper',['SerializationHelper',['../class_level_serializer_1_1_serialization_helper.html',1,'LevelSerializer']]],
  ['serializationpriorityattribute',['SerializationPriorityAttribute',['../class_serialization_1_1_serialization_priority_attribute.html',1,'Serialization']]],
  ['serializationscope',['SerializationScope',['../class_serialization_1_1_unity_serializer_1_1_serialization_scope.html',1,'Serialization::UnitySerializer']]],
  ['serializationsplitscope',['SerializationSplitScope',['../class_serialization_1_1_unity_serializer_1_1_serialization_split_scope.html',1,'Serialization::UnitySerializer']]],
  ['serializationsuspendedexception',['SerializationSuspendedException',['../class_level_serializer_1_1_serialization_suspended_exception.html',1,'LevelSerializer']]],
  ['serializeall',['SerializeAll',['../class_serialize_all.html',1,'']]],
  ['serializeanimations',['SerializeAnimations',['../class_serialize_animations.html',1,'']]],
  ['serializeanimationstate',['SerializeAnimationState',['../class_serialize_animation_state.html',1,'']]],
  ['serializeanimator',['SerializeAnimator',['../class_serialize_animator.html',1,'']]],
  ['serializeareaeffector2d',['SerializeAreaEffector2D',['../class_serialize_area_effector2_d.html',1,'']]],
  ['serializeassetreference',['SerializeAssetReference',['../class_serialize_asset_reference.html',1,'']]],
  ['serializeaudiochorusfilter',['SerializeAudioChorusFilter',['../class_serialize_audio_chorus_filter.html',1,'']]],
  ['serializeaudiodistortionfilter',['SerializeAudioDistortionFilter',['../class_serialize_audio_distortion_filter.html',1,'']]],
  ['serializeaudioechofilter',['SerializeAudioEchoFilter',['../class_serialize_audio_echo_filter.html',1,'']]],
  ['serializeaudiohighpassfilter',['SerializeAudioHighPassFilter',['../class_serialize_audio_high_pass_filter.html',1,'']]],
  ['serializeaudiolowpassfilter',['SerializeAudioLowPassFilter',['../class_serialize_audio_low_pass_filter.html',1,'']]],
  ['serializebounds',['SerializeBounds',['../class_serialize_bounds.html',1,'']]],
  ['serializeboxcollider',['SerializeBoxCollider',['../class_serialize_box_collider.html',1,'']]],
  ['serializeboxcollider2d',['SerializeBoxCollider2D',['../class_serialize_box_collider2_d.html',1,'']]],
  ['serializebuoyancyeffector2d',['SerializeBuoyancyEffector2D',['../class_serialize_buoyancy_effector2_d.html',1,'']]],
  ['serializecamera',['SerializeCamera',['../class_serialize_camera.html',1,'']]],
  ['serializecapsulecollider',['SerializeCapsuleCollider',['../class_serialize_capsule_collider.html',1,'']]],
  ['serializecirclecollider2d',['SerializeCircleCollider2D',['../class_serialize_circle_collider2_d.html',1,'']]],
  ['serializecollider',['SerializeCollider',['../class_serialize_collider.html',1,'']]],
  ['serializecolor',['SerializeColor',['../class_serialize_color.html',1,'']]],
  ['serializecomponentreference',['SerializeComponentReference',['../class_serialize_component_reference.html',1,'']]],
  ['serializedistancejoint2d',['SerializeDistanceJoint2D',['../class_serialize_distance_joint2_d.html',1,'']]],
  ['serializeedgecollider2d',['SerializeEdgeCollider2D',['../class_serialize_edge_collider2_d.html',1,'']]],
  ['serializeeventsystem',['SerializeEventSystem',['../class_serialize_event_system.html',1,'']]],
  ['serializefixedjoint2d',['SerializeFixedJoint2D',['../class_serialize_fixed_joint2_d.html',1,'']]],
  ['serializefrictionjoint2d',['SerializeFrictionJoint2D',['../class_serialize_friction_joint2_d.html',1,'']]],
  ['serializegameobjectreference',['SerializeGameObjectReference',['../class_serialize_game_object_reference.html',1,'']]],
  ['serializehingejoint2d',['SerializeHingeJoint2D',['../class_serialize_hinge_joint2_d.html',1,'']]],
  ['serializelinerenderer',['SerializeLineRenderer',['../class_serialize_line_renderer.html',1,'']]],
  ['serializematerial',['SerializeMaterial',['../class_serialize_material.html',1,'']]],
  ['serializemeshcollider',['SerializeMeshCollider',['../class_serialize_mesh_collider.html',1,'']]],
  ['serializenavmeshagent',['SerializeNavMeshAgent',['../class_serialize_nav_mesh_agent.html',1,'']]],
  ['serializeplatformeffector2d',['SerializePlatformEffector2D',['../class_serialize_platform_effector2_d.html',1,'']]],
  ['serializepointeffector2d',['SerializePointEffector2D',['../class_serialize_point_effector2_d.html',1,'']]],
  ['serializepolygoncollider2d',['SerializePolygonCollider2D',['../class_serialize_polygon_collider2_d.html',1,'']]],
  ['serializeprivatefieldoftype',['SerializePrivateFieldOfType',['../class_serialization_1_1_serialize_private_field_of_type.html',1,'Serialization']]],
  ['serializequaternion',['SerializeQuaternion',['../class_serialize_quaternion.html',1,'']]],
  ['serializerattribute',['SerializerAttribute',['../class_serialization_1_1_serializer_attribute.html',1,'Serialization']]],
  ['serializerelativejoint2d',['SerializeRelativeJoint2D',['../class_serialize_relative_joint2_d.html',1,'']]],
  ['serializerenderer',['SerializeRenderer',['../class_serialize_renderer.html',1,'']]],
  ['serializerextensionbase',['SerializerExtensionBase',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20animationstate_20_3e',['SerializerExtensionBase&lt; AnimationState &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20bounds_20_3e',['SerializerExtensionBase&lt; Bounds &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20color_20_3e',['SerializerExtensionBase&lt; Color &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20component_20_3e',['SerializerExtensionBase&lt; Component &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20gameobject_20_3e',['SerializerExtensionBase&lt; GameObject &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20material_20_3e',['SerializerExtensionBase&lt; Material &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20object_20_3e',['SerializerExtensionBase&lt; object &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20quaternion_20_3e',['SerializerExtensionBase&lt; Quaternion &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20texture2d_20_3e',['SerializerExtensionBase&lt; Texture2D &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20vector2_20_3e',['SerializerExtensionBase&lt; Vector2 &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20vector3_20_3e',['SerializerExtensionBase&lt; Vector3 &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20vector4_20_3e',['SerializerExtensionBase&lt; Vector4 &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerextensionbase_3c_20waitforseconds_20_3e',['SerializerExtensionBase&lt; WaitForSeconds &gt;',['../class_serializer_extension_base.html',1,'']]],
  ['serializerid',['SerializerId',['../class_serialization_1_1_serializer_id.html',1,'Serialization']]],
  ['serializerigidbody',['SerializeRigidBody',['../class_serialize_rigid_body.html',1,'']]],
  ['serializerigidbody2d',['SerializeRigidBody2D',['../class_serialize_rigid_body2_d.html',1,'']]],
  ['serializerplugin',['SerializerPlugIn',['../class_serializer_plug_in.html',1,'']]],
  ['serializescriptableobjectreference',['SerializeScriptableObjectReference',['../class_serialize_scriptable_object_reference.html',1,'']]],
  ['serializeskinnedmeshrenderer',['SerializeSkinnedMeshRenderer',['../class_serialize_skinned_mesh_renderer.html',1,'']]],
  ['serializesliderjoint2d',['SerializeSliderJoint2D',['../class_serialize_slider_joint2_d.html',1,'']]],
  ['serializespherecollider',['SerializeSphereCollider',['../class_serialize_sphere_collider.html',1,'']]],
  ['serializespringjoint2d',['SerializeSpringJoint2D',['../class_serialize_spring_joint2_d.html',1,'']]],
  ['serializesurfaceeffector2d',['SerializeSurfaceEffector2D',['../class_serialize_surface_effector2_d.html',1,'']]],
  ['serializeterrain',['SerializeTerrain',['../class_serialize_terrain.html',1,'']]],
  ['serializetexture2d',['SerializeTexture2D',['../class_serialize_texture2_d.html',1,'']]],
  ['serializethis',['SerializeThis',['../class_serialize_this.html',1,'']]],
  ['serializetrailrenderer',['SerializeTrailRenderer',['../class_serialize_trail_renderer.html',1,'']]],
  ['serializevector2',['SerializeVector2',['../class_serialize_vector2.html',1,'']]],
  ['serializevector3',['SerializeVector3',['../class_serialize_vector3.html',1,'']]],
  ['serializevector4',['SerializeVector4',['../class_serialize_vector4.html',1,'']]],
  ['serializewaitforseconds',['SerializeWaitForSeconds',['../class_serialize_wait_for_seconds.html',1,'']]],
  ['serializewheelcollider',['SerializeWheelCollider',['../class_serialize_wheel_collider.html',1,'']]],
  ['serializewheeljoint2d',['SerializeWheelJoint2D',['../class_serialize_wheel_joint2_d.html',1,'']]],
  ['sharedarray',['SharedArray',['../class_shared_memory_1_1_shared_array.html',1,'SharedMemory']]],
  ['sharedbuffer',['SharedBuffer',['../class_shared_memory_1_1_shared_buffer.html',1,'SharedMemory']]],
  ['sharedheader',['SharedHeader',['../struct_shared_memory_1_1_shared_header.html',1,'SharedMemory']]],
  ['sharpzipbaseexception',['SharpZipBaseException',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_sharp_zip_base_exception.html',1,'ICSharpCode::SharpZipLib']]],
  ['singlethreadsynchronizationcontext',['SingleThreadSynchronizationContext',['../class_minimu_async_bridge_unit_test_1_1_single_thread_synchronization_context.html',1,'MinimuAsyncBridgeUnitTest']]],
  ['smoothfloat',['SmoothFloat',['../class_radical_library_1_1_smooth_float.html',1,'RadicalLibrary']]],
  ['smoothfollow',['SmoothFollow',['../class_unity_standard_assets_1_1_utility_1_1_smooth_follow.html',1,'UnityStandardAssets::Utility']]],
  ['smoothquaternion',['SmoothQuaternion',['../class_radical_library_1_1_smooth_quaternion.html',1,'RadicalLibrary']]],
  ['smoothvector3',['SmoothVector3',['../class_radical_library_1_1_smooth_vector3.html',1,'RadicalLibrary']]],
  ['socketclient',['SocketClient',['../class_lerp2_a_p_i_1_1_communication_1_1_sockets_1_1_socket_client.html',1,'Lerp2API::Communication::Sockets']]],
  ['socketmessage',['SocketMessage',['../class_lerp2_a_p_i_1_1_communication_1_1_sockets_1_1_socket_message.html',1,'Lerp2API::Communication::Sockets']]],
  ['socketserver',['SocketServer',['../class_lerp2_a_p_i_1_1_communication_1_1_sockets_1_1_socket_server.html',1,'Lerp2API::Communication::Sockets']]],
  ['specialist',['Specialist',['../class_serialization_1_1_specialist.html',1,'Serialization']]],
  ['specialistprovider',['SpecialistProvider',['../class_serialization_1_1_specialist_provider.html',1,'Serialization']]],
  ['standaloneinput',['StandaloneInput',['../class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_standalone_input.html',1,'UnityStandardAssets::CrossPlatformInput::PlatformSpecific']]],
  ['statemachineattribute',['StateMachineAttribute',['../class_system_1_1_runtime_1_1_compiler_services_1_1_state_machine_attribute.html',1,'System::Runtime::CompilerServices']]],
  ['staticdiskdatasource',['StaticDiskDataSource',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_zip_1_1_static_disk_data_source.html',1,'ICSharpCode::SharpZipLib::Zip']]],
  ['storeanimator',['StoreAnimator',['../class_store_animator.html',1,'']]],
  ['storecomponent',['StoreComponent',['../class_store_component.html',1,'']]],
  ['storeddata',['StoredData',['../class_level_serializer_1_1_stored_data.html',1,'LevelSerializer']]],
  ['storedentry',['StoredEntry',['../class_save_game_manager_1_1_stored_entry.html',1,'SaveGameManager']]],
  ['storedinfo',['StoredInfo',['../class_serialize_nav_mesh_agent_1_1_stored_info.html',1,'SerializeNavMeshAgent']]],
  ['storedinformation',['StoredInformation',['../class_serialize_audio_high_pass_filter_1_1_stored_information.html',1,'SerializeAudioHighPassFilter.StoredInformation'],['../class_serialize_audio_low_pass_filter_1_1_stored_information.html',1,'SerializeAudioLowPassFilter.StoredInformation'],['../class_serialize_hinge_joint2_d_1_1_stored_information.html',1,'SerializeHingeJoint2D.StoredInformation'],['../class_serialize_wheel_collider_1_1_stored_information.html',1,'SerializeWheelCollider.StoredInformation'],['../class_serialize_trail_renderer_1_1_stored_information.html',1,'SerializeTrailRenderer.StoredInformation'],['../class_serialize_spring_joint2_d_1_1_stored_information.html',1,'SerializeSpringJoint2D.StoredInformation'],['../class_serialize_wheel_joint2_d_1_1_stored_information.html',1,'SerializeWheelJoint2D.StoredInformation'],['../class_serialize_friction_joint2_d_1_1_stored_information.html',1,'SerializeFrictionJoint2D.StoredInformation'],['../class_serialize_event_system_1_1_stored_information.html',1,'SerializeEventSystem.StoredInformation'],['../class_serialize_edge_collider2_d_1_1_stored_information.html',1,'SerializeEdgeCollider2D.StoredInformation'],['../class_serialize_skinned_mesh_renderer_1_1_stored_information.html',1,'SerializeSkinnedMeshRenderer.StoredInformation'],['../class_serialize_audio_chorus_filter_1_1_stored_information.html',1,'SerializeAudioChorusFilter.StoredInformation'],['../class_serialize_distance_joint2_d_1_1_stored_information.html',1,'SerializeDistanceJoint2D.StoredInformation'],['../class_serialize_audio_distortion_filter_1_1_stored_information.html',1,'SerializeAudioDistortionFilter.StoredInformation'],['../class_serialize_box_collider2_d_1_1_stored_information.html',1,'SerializeBoxCollider2D.StoredInformation'],['../class_serialize_audio_echo_filter_1_1_stored_information.html',1,'SerializeAudioEchoFilter.StoredInformation'],['../class_serialize_line_renderer_1_1_stored_information.html',1,'SerializeLineRenderer.StoredInformation'],['../class_serialize_fixed_joint2_d_1_1_stored_information.html',1,'SerializeFixedJoint2D.StoredInformation'],['../class_serialize_relative_joint2_d_1_1_stored_information.html',1,'SerializeRelativeJoint2D.StoredInformation'],['../class_serialize_slider_joint2_d_1_1_stored_information.html',1,'SerializeSliderJoint2D.StoredInformation'],['../class_serialize_circle_collider2_d_1_1_stored_information.html',1,'SerializeCircleCollider2D.StoredInformation'],['../class_serialize_polygon_collider2_d_1_1_stored_information.html',1,'SerializePolygonCollider2D.StoredInformation'],['../class_serialize_renderer_1_1_stored_information.html',1,'SerializeRenderer.StoredInformation']]],
  ['storeditem',['StoredItem',['../class_level_serializer_1_1_stored_item.html',1,'LevelSerializer']]],
  ['storedreferences',['StoredReferences',['../class_stored_references.html',1,'']]],
  ['storedstate',['StoredState',['../class_serialize_animations_1_1_stored_state.html',1,'SerializeAnimations']]],
  ['storedvalue',['StoredValue',['../class_store_materials_1_1_stored_value.html',1,'StoreMaterials']]],
  ['storeinformation',['StoreInformation',['../class_store_information.html',1,'']]],
  ['storematerials',['StoreMaterials',['../class_store_materials.html',1,'']]],
  ['storemesh',['StoreMesh',['../class_store_mesh.html',1,'']]],
  ['strangecrc',['StrangeCRC',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_checksums_1_1_strange_c_r_c.html',1,'ICSharpCode::SharpZipLib::Checksums']]],
  ['streammanipulator',['StreamManipulator',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_zip_1_1_compression_1_1_streams_1_1_stream_manipulator.html',1,'ICSharpCode::SharpZipLib::Zip::Compression::Streams']]],
  ['streamutils',['StreamUtils',['../class_i_c_sharp_code_1_1_sharp_zip_lib_1_1_core_1_1_stream_utils.html',1,'ICSharpCode::SharpZipLib::Core']]],
  ['subtypeserializerattribute',['SubTypeSerializerAttribute',['../class_serialization_1_1_sub_type_serializer_attribute.html',1,'Serialization']]],
  ['suspendlevelserialization',['SuspendLevelSerialization',['../class_suspend_level_serialization.html',1,'']]]
];
